### ISSUE TITLE
dmsg Client should be instantiated in singleton.

### ISSUE THREAD

**Issue by evanlinjin** [SkycoinProject/dmsg-http#9]
We are creating multiple instances of `dmsg.Client` within the library, where only one instance of `dmsg.Client` is expected per user (or per computer).

Once should implement the singleton pattern to instantiate `dmsg.Client`.

**Comment by Chris-PS** [comment]
Thanks, @sn-srdjan will take care of it.

**Comment by Chris-PS** [comment]
Should be done. But, not as requested - per computer - but per transport. We figured that would be a more elegant solution in case of multiple instances per PC (for testing etc.). If that is not ok, let us know @evanlinjin .
